// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DebugChats() {
  return window['go']['main']['App']['DebugChats']();
}

export function GetAllTargets() {
  return window['go']['main']['App']['GetAllTargets']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetDefaultTimes() {
  return window['go']['main']['App']['GetDefaultTimes']();
}

export function GetLogFile() {
  return window['go']['main']['App']['GetLogFile']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMealEndHours() {
  return window['go']['main']['App']['GetMealEndHours']();
}

export function GetSavedConfig() {
  return window['go']['main']['App']['GetSavedConfig']();
}

export function GetSchedule() {
  return window['go']['main']['App']['GetSchedule']();
}

export function GetStoreConfig() {
  return window['go']['main']['App']['GetStoreConfig']();
}

export function GetThumbRefreshWindows() {
  return window['go']['main']['App']['GetThumbRefreshWindows']();
}

export function GetTodayMeal() {
  return window['go']['main']['App']['GetTodayMeal']();
}

export function GetWeekMeal(arg1) {
  return window['go']['main']['App']['GetWeekMeal'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ResetAll() {
  return window['go']['main']['App']['ResetAll']();
}

export function SearchStore(arg1, arg2) {
  return window['go']['main']['App']['SearchStore'](arg1, arg2);
}

export function SendMealToChat(arg1) {
  return window['go']['main']['App']['SendMealToChat'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetSchedule(arg1, arg2) {
  return window['go']['main']['App']['SetSchedule'](arg1, arg2);
}

export function SetStore(arg1, arg2) {
  return window['go']['main']['App']['SetStore'](arg1, arg2);
}

export function WaitForLogin() {
  return window['go']['main']['App']['WaitForLogin']();
}
