// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function DebugChats():Promise<string>;

export function GetAllTargets():Promise<Array<main.SendTarget>>;

export function GetAutoStart():Promise<boolean>;

export function GetLogFile():Promise<string>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetSavedConfig():Promise<main.AppConfig>;

export function GetSchedule():Promise<main.Schedule>;

export function GetStoreConfig():Promise<Record<string, string>>;

export function GetTodayMeal():Promise<Record<string, any>>;

export function GetWeekMeal(arg1:number):Promise<Record<string, any>>;

export function HideWindow():Promise<void>;

export function IsLoggedIn():Promise<boolean>;

export function Login():Promise<main.DeviceCode>;

export function Logout():Promise<void>;

export function QuitApp():Promise<void>;

export function ResetAll():Promise<void>;

export function SearchStore(arg1:string,arg2:number):Promise<main.StoreSearchResult>;

export function SendMealToChat(arg1:string):Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetSchedule(arg1:string,arg2:string):Promise<void>;

export function SetStore(arg1:string,arg2:string):Promise<void>;

export function WaitForLogin():Promise<void>;
